//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Collect.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CustomEntities : DbContext
    {
        public CustomEntities()
            : base("name=CustomEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CE> CEs { get; set; }
        public virtual DbSet<Clist> Clists { get; set; }
        public virtual DbSet<Creq> Creqs { get; set; }
        public virtual DbSet<Emp> Emps { get; set; }
    }
}
